In [2]:
import pandas as pd
import numpy as np

## dataframe and it's basic functions

In [3]:
df = pd.DataFrame([[1,2,3],[4,5,6], [7,8,9]], columns = ['a', 'b', 'c'], index = ["x", "y", "z"])
print(df.head())
print(df.columns)  # prints features or column names in this case
print(df.index.tolist()) # Prints index  default indexes starts are like 01234 etc
print(df.info()) # provides basic info about the dataframe
print(df.describe()) # provides basic statstical info about the dataframe
print(df['a'].unique) # provides unique value in the respective column
print(df.shape) # gives away the shape of the column (rows, columns)

   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9
Index(['a', 'b', 'c'], dtype='object')
['x', 'y', 'z']
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes
None
         a    b    c
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0
<bound method Series.unique of x    1
y    4
z    7
Name: a, dtype: int64>
(3, 3)

## working on real data

In [4]:
states = pd.read_csv("datasets/states.csv")
states.head()  # states.tail() to get last five rows of the dataset

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
0,Alabama,21252,3456,0.6,69.93,4.3,68.1,173
1,Alaska,18170,3356,2.0,68.22,2.4,45.5,154
2,Arizona,1169,5298,1.0,72.55,9.2,44.9,150
3,Arkansas,9415,6315,2.7,73.31,3.4,54.0,71
4,California,5394,3881,2.9,70.36,2.4,39.4,88

In [5]:
states.sample(10, random_state=1)  # get 10 random samples from the data, random_state can be changed

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
27,Nevada,2626,5899,2.1,69.60,14.6,73.7,18
35,Oklahoma,2221,3674,1.4,74.90,5.0,70.3,116
40,South Dakota,4228,6856,2.7,69.72,9.9,62.9,107
38,Rhode Island,10576,3234,0.6,71.34,14.8,58.9,14
2,Arizona,1169,5298,1.0,72.55,9.2,44.9,150
3,Arkansas,9415,6315,2.7,73.31,3.4,54.0,71
48,Wisconsin,11535,3833,2.2,73.97,8.6,46.3,13
29,New Jersey,19181,4936,1.1,71.31,7.1,39.2,168
46,Washington,17632,3032,2.2,71.88,15.0,39.7,34
31,New York,3524,3248,1.5,70.38,13.9,46.2,48

## loc and iloc

In [6]:
states.loc[[0,1,5]]  # gets 0th 1st and 5th rows from the dataset
#  we can also use slice index [0:3] or like [0:] to get all rows

      State  Population  Income  Illiteracy  Life_Exp  Murder  HS_Grad  Frost
0   Alabama       21252    3456         0.6     69.93     4.3     68.1    173
1    Alaska       18170    3356         2.0     68.22     2.4     45.5    154
5  Colorado       20082    4083         2.5     73.11     9.0     78.8     96

In [7]:
# we can also grab columns as well from it for example [5:8, ['State', 'Population']]
states.loc[0:5, ['State', 'Population']]

        State  Population
0     Alabama       21252
1      Alaska       18170
2     Arizona        1169
3    Arkansas        9415
4  California        5394
5    Colorado       20082

In [8]:
# Iloc function only works on indexes, it doesn't take strings as arguments
states.iloc[0:5,:-1] # selects 5 rows and all columns (except the last)

        State  Population  Income  Illiteracy  Life_Exp  Murder  HS_Grad
0     Alabama       21252    3456         0.6     69.93     4.3     68.1
1      Alaska       18170    3356         2.0     68.22     2.4     45.5
2     Arizona        1169    5298         1.0     72.55     9.2     44.9
3    Arkansas        9415    6315         2.7     73.31     3.4     54.0
4  California        5394    3881         2.9     70.36     2.4     39.4

In [9]:
# we can remove the indexes 0123 on the left side by using .index
# states.index = states["State"]
# states.head()
# but the loc function will not work normally due to absence of index we need to select 
# the row by typing the index string

In [10]:
# for example
# states.loc["Alabama":"California", ["State", "Income"]]

In [11]:
# we can also change specific value using loc function
states.loc[0, "Income"] = 4456
states.loc[0]
# we can also grab specific values using iat or at function

State         Alabama
Population      21252
Income           4456
Illiteracy        0.6
Life_Exp        69.93
Murder            4.3
HS_Grad          68.1
Frost             173
Name: 0, dtype: object

In [12]:
# grabbing a specific column
states.loc[:5, "Income"]

0    4456
1    3356
2    5298
3    6315
4    3881
5    4083
Name: Income, dtype: int64

In [13]:
# sorting the column values
states.sort_values("Income", ascending = False)

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
19,Maryland,8930,6980,1.8,69.25,14.7,74.2,76
40,South Dakota,4228,6856,2.7,69.72,9.9,62.9,107
34,Ohio,3356,6794,2.4,69.65,7.1,56.7,102
21,Michigan,17678,6762,0.5,70.27,1.3,76.8,78
11,Idaho,10926,6452,2.4,68.39,13.3,71.2,102
3,Arkansas,9415,6315,2.7,73.31,3.4,54.0,71
33,North Dakota,14820,6309,2.7,71.85,1.8,80.0,3
23,Mississippi,17755,6136,0.8,72.62,15.2,42.4,135
27,Nevada,2626,5899,2.1,69.60,14.6,73.7,18
9,Georgia,9048,5874,2.8,72.54,10.1,42.7,186
17,Louisiana,676,5786,2.3,72.77,9.1,47.0,164
49,Wyoming,3324,5598,1.6,69.94,1.1,69.7,163
16,Kentucky,14133,5442,0.7,70.67,15.9,58.8,141
41,Tennessee,21840,5390,1.9,70.21,4.9,65.1,80
2,Arizona,1169,5298,1.0,72.55,9.2,44.9,150
6,Connecticut,2882,5261,1.2,72.40,14.3,51.3,49
14,Iowa,18694,5207,1.2,72.09,14.5,53.0,56
15,Kansas,4832,5087,1.7,73.29,13.9,41.9,40
20,Massachusetts,21237,5079,2.0,69.07,12.4,59.3,199
29,New Jersey,19181,4936,1.1,71.31,7.1,39.2,168
32,North Carolina,17873,4837,0.9,69.28,7.9,74.4,19
45,Virginia,5469,4794,2.6,72.92,10.2,79.4,167
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
36,Oregon,9647,4732,2.2,73.11,12.8,64.8,124
25,Montana,10514,4634,3.0,72.55,7.6,58.3,30
13,Indiana,16658,4620,2.7,72.50,3.1,41.3,190
0,Alabama,21252,4456,0.6,69.93,4.3,68.1,173
30,New Mexico,14424,4451,1.6,71.27,11.9,65.3,165
8,Florida,12755,4138,1.6,73.84,3.4,51.0,171
42,Texas,8121,4087,1.5,72.70,5.5,49.2,192
44,Vermont,16876,4086,0.8,70.44,2.0,46.0,72
5,Colorado,20082,4083,2.5,73.11,9.0,78.8,96
28,New Hampshire,17147,3974,1.2,71.40,9.1,67.6,146
26,Nebraska,8423,3920,0.7,68.15,9.3,61.5,1
4,California,5394,3881,2.9,70.36,2.4,39.4,88
48,Wisconsin,11535,3833,2.2,73.97,8.6,46.3,13
37,Pennsylvania,5372,3777,1.2,74.78,9.7,59.4,191
35,Oklahoma,2221,3674,1.4,74.90,5.0,70.3,116
10,Hawaii,8321,3669,1.7,69.89,14.9,66.0,56
47,West Virginia,8966,3472,2.7,73.20,3.3,47.7,53
18,Maine,11446,3456,1.2,69.11,1.0,67.5,184
1,Alaska,18170,3356,2.0,68.22,2.4,45.5,154
39,South Carolina,16940,3328,2.6,68.48,2.0,73.8,103
12,Illinois,9073,3271,1.0,74.60,14.1,49.2,167
31,New York,3524,3248,1.5,70.38,13.9,46.2,48
22,Minnesota,8146,3237,1.1,71.97,2.2,67.9,17
38,Rhode Island,10576,3234,0.6,71.34,14.8,58.9,14
7,Delaware,2579,3187,2.2,73.41,15.8,73.5,25
43,Utah,2677,3038,1.6,74.99,15.9,38.3,54
46,Washington,17632,3032,2.2,71.88,15.0,39.7,34

In [14]:
# iterating all rows in the dataset
# for index, row in states.iterrows():
#     print(index)
#     print(row)
#     print("\n\n\n\n")
#avoid using it

## filtering data

In [15]:
# lets grab the rows that have a frost of more than 150 and grab only State and Population
states.loc[states["Frost"] > 170, ["State", "Population", "Frost"]]

            State  Population  Frost
0         Alabama       21252    173
8         Florida       12755    171
9         Georgia        9048    186
13        Indiana       16658    190
18          Maine       11446    184
20  Massachusetts       21237    199
24       Missouri       20176    182
37   Pennsylvania        5372    191
42          Texas        8121    192

In [16]:
# to make it more easier we can use
states[states["Frost"]>170]

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
0,Alabama,21252,4456,0.6,69.93,4.3,68.1,173
8,Florida,12755,4138,1.6,73.84,3.4,51.0,171
9,Georgia,9048,5874,2.8,72.54,10.1,42.7,186
13,Indiana,16658,4620,2.7,72.50,3.1,41.3,190
18,Maine,11446,3456,1.2,69.11,1.0,67.5,184
20,Massachusetts,21237,5079,2.0,69.07,12.4,59.3,199
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
37,Pennsylvania,5372,3777,1.2,74.78,9.7,59.4,191
42,Texas,8121,4087,1.5,72.70,5.5,49.2,192

In [17]:
# applying multiple conditons  frost > 170 & life expectancy > 70
states[(states["Frost"]>170) & (states["Life_Exp"] > 70)]

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
8,Florida,12755,4138,1.6,73.84,3.4,51.0,171
9,Georgia,9048,5874,2.8,72.54,10.1,42.7,186
13,Indiana,16658,4620,2.7,72.50,3.1,41.3,190
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
37,Pennsylvania,5372,3777,1.2,74.78,9.7,59.4,191
42,Texas,8121,4087,1.5,72.70,5.5,49.2,192

In [18]:
# applying string functions to make it look more fancy
# all string function will be used in .str.func() format
states[states["State"].str.contains("M")]

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
18,Maine,11446,3456,1.2,69.11,1.0,67.5,184
19,Maryland,8930,6980,1.8,69.25,14.7,74.2,76
20,Massachusetts,21237,5079,2.0,69.07,12.4,59.3,199
21,Michigan,17678,6762,0.5,70.27,1.3,76.8,78
22,Minnesota,8146,3237,1.1,71.97,2.2,67.9,17
23,Mississippi,17755,6136,0.8,72.62,15.2,42.4,135
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
25,Montana,10514,4634,3.0,72.55,7.6,58.3,30
30,New Mexico,14424,4451,1.6,71.27,11.9,65.3,165

In [19]:
states[states["State"].str.startswith("M")]

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
18,Maine,11446,3456,1.2,69.11,1.0,67.5,184
19,Maryland,8930,6980,1.8,69.25,14.7,74.2,76
20,Massachusetts,21237,5079,2.0,69.07,12.4,59.3,199
21,Michigan,17678,6762,0.5,70.27,1.3,76.8,78
22,Minnesota,8146,3237,1.1,71.97,2.2,67.9,17
23,Mississippi,17755,6136,0.8,72.62,15.2,42.4,135
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
25,Montana,10514,4634,3.0,72.55,7.6,58.3,30

In [20]:
# query function
states.query("State == 'Maine'")

    State  Population  Income  Illiteracy  Life_Exp  Murder  HS_Grad  Frost
18  Maine       11446    3456         1.2     69.11     1.0     67.5    184

In [21]:
states.query("Frost > 170 and Income > 4000")

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost
0,Alabama,21252,4456,0.6,69.93,4.3,68.1,173
8,Florida,12755,4138,1.6,73.84,3.4,51.0,171
9,Georgia,9048,5874,2.8,72.54,10.1,42.7,186
13,Indiana,16658,4620,2.7,72.50,3.1,41.3,190
20,Massachusetts,21237,5079,2.0,69.07,12.4,59.3,199
24,Missouri,20176,4733,2.9,74.50,12.3,66.0,182
42,Texas,8121,4087,1.5,72.70,5.5,49.2,192

## adding and removing rows and columns

In [22]:
# Adding an new column
# creating a random array
arr = []
arr2 = []
for i in range(0,50):
    n1 = np.random.randint(5,15)
    arr.append(n1)
    n2 = np.random.randint(5,15)
    arr2.append(n2)

states["Price"] = arr2
states["coffe_price"] = arr 

states.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,HS_Grad,Frost,Price,coffe_price
0,Alabama,21252,4456,0.6,69.93,4.3,68.1,173,7,6
1,Alaska,18170,3356,2.0,68.22,2.4,45.5,154,8,13
2,Arizona,1169,5298,1.0,72.55,9.2,44.9,150,6,7
3,Arkansas,9415,6315,2.7,73.31,3.4,54.0,71,5,12
4,California,5394,3881,2.9,70.36,2.4,39.4,88,6,6

In [23]:
# dropping a column
states.drop(columns = ["HS_Grad"], inplace = True)
states.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,Price,coffe_price
0,Alabama,21252,4456,0.6,69.93,4.3,173,7,6
1,Alaska,18170,3356,2.0,68.22,2.4,154,8,13
2,Arizona,1169,5298,1.0,72.55,9.2,150,6,7
3,Arkansas,9415,6315,2.7,73.31,3.4,71,5,12
4,California,5394,3881,2.9,70.36,2.4,88,6,6

In [24]:
# we can use copy function to copy one dataset into another
states_new = states.copy()
states_new["Zero_column"] = 0
states_new.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,Price,coffe_price,Zero_column
0,Alabama,21252,4456,0.6,69.93,4.3,173,7,6,0
1,Alaska,18170,3356,2.0,68.22,2.4,154,8,13,0
2,Arizona,1169,5298,1.0,72.55,9.2,150,6,7,0
3,Arkansas,9415,6315,2.7,73.31,3.4,71,5,12,0
4,California,5394,3881,2.9,70.36,2.4,88,6,6,0

In [25]:
# some calculations
states_new.drop(columns = ["Zero_column"], inplace = True)
states_new["final_price"] = states_new["Price"] * states_new["coffe_price"]
states_new.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,Price,coffe_price,final_price
0,Alabama,21252,4456,0.6,69.93,4.3,173,7,6,42
1,Alaska,18170,3356,2.0,68.22,2.4,154,8,13,104
2,Arizona,1169,5298,1.0,72.55,9.2,150,6,7,42
3,Arkansas,9415,6315,2.7,73.31,3.4,71,5,12,60
4,California,5394,3881,2.9,70.36,2.4,88,6,6,36

In [26]:
# Rename a column
states_new.rename(columns = {"State":'state', "Population":"Amount of People"}, inplace = True)
states_new.head(5)

,state,Amount of People,Income,Illiteracy,Life_Exp,Murder,Frost,Price,coffe_price,final_price
0,Alabama,21252,4456,0.6,69.93,4.3,173,7,6,42
1,Alaska,18170,3356,2.0,68.22,2.4,154,8,13,104
2,Arizona,1169,5298,1.0,72.55,9.2,150,6,7,42
3,Arkansas,9415,6315,2.7,73.31,3.4,71,5,12,60
4,California,5394,3881,2.9,70.36,2.4,88,6,6,36

In [27]:
# convering date column to datetime data type
# removing excess columns
states_new.drop(columns = ["Murder", "Illiteracy", "Price", "coffe_price", "final_price"], inplace=True)
# creating date column
states_new["date"] = "1964-12-24"
states_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             50 non-null     object
 1   Amount of People  50 non-null     int64
 2   Income            50 non-null     int64
 3   Life_Exp          50 non-null     float64
 4   Frost             50 non-null     int64
 5   date              50 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 2.5+ KB

In [28]:
# converting object date to real date
states_new["date"] = pd.to_datetime(states_new['date'])
states_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             50 non-null     object
 1   Amount of People  50 non-null     int64
 2   Income            50 non-null     int64
 3   Life_Exp          50 non-null     float64
 4   Frost             50 non-null     int64
 5   date              50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 2.5+ KB

In [29]:
# now we can separate the year, month and date
# all functions of datetime will be use in .dt.func() format
states_new["born_year"] = states_new["date"].dt.year
states_new[["state", "born_year"]].head(5)  # another simple of of displaying or selecting sepcific columns

        state  born_year
0     Alabama       1964
1      Alaska       1964
2     Arizona       1964
3    Arkansas       1964
4  California       1964

In [30]:
# saving data to a csv file
states_new.to_csv("datasets/states_new.csv", index = False)
# don't use .csv extension if you just want to export a simple file

In [31]:
# applying lambda functions and adding it to a new column
states.drop(columns = ["coffe_price", "Price"], inplace = True)
states.head()

        State  Population  Income  Illiteracy  Life_Exp  Murder  Frost
0     Alabama       21252    4456         0.6     69.93     4.3    173
1      Alaska       18170    3356         2.0     68.22     2.4    154
2     Arizona        1169    5298         1.0     72.55     9.2    150
3    Arkansas        9415    6315         2.7     73.31     3.4     71
4  California        5394    3881         2.9     70.36     2.4     88

In [32]:
states["remarks"] = states["Life_Exp"].apply(lambda x: "not good" if x < 70 else ("average" if x < 72 else "Good"))
states.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,remarks
0,Alabama,21252,4456,0.6,69.93,4.3,173,not good
1,Alaska,18170,3356,2.0,68.22,2.4,154,not good
2,Arizona,1169,5298,1.0,72.55,9.2,150,Good
3,Arkansas,9415,6315,2.7,73.31,3.4,71,Good
4,California,5394,3881,2.9,70.36,2.4,88,average

In [33]:
# add a custom function that give a remark to murder rate from low to medium to high
# hint : state["m_remarks"] = states.apply(func_name, axis = 1)

## merging and concatenating Data

In [34]:
merg_data = pd.merge(states, states_new, left_on = "Life_Exp", right_on = "Life_Exp", how = "inner")
# we can also use left, right, all kinds of join in the SQL
merg_data.head()

,State,Population,Income_x,Illiteracy,Life_Exp,Murder,Frost_x,remarks,state,Amount of People,Income_y,Frost_y,date,born_year
0,Alabama,21252,4456,0.6,69.93,4.3,173,not good,Alabama,21252,4456,173,1964-12-24,1964
1,Alaska,18170,3356,2.0,68.22,2.4,154,not good,Alaska,18170,3356,154,1964-12-24,1964
2,Arizona,1169,5298,1.0,72.55,9.2,150,Good,Arizona,1169,5298,150,1964-12-24,1964
3,Arizona,1169,5298,1.0,72.55,9.2,150,Good,Montana,10514,4634,30,1964-12-24,1964
4,Montana,10514,4634,3.0,72.55,7.6,30,Good,Arizona,1169,5298,150,1964-12-24,1964

In [35]:
# another filtering tech
more_death = states[states["Murder"] > 7.0].copy()
more_frost = states[states["Frost"] > 170].copy()
more_death.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,remarks
2,Arizona,1169,5298,1.0,72.55,9.2,150,Good
5,Colorado,20082,4083,2.5,73.11,9.0,96,Good
6,Connecticut,2882,5261,1.2,72.40,14.3,49,Good
7,Delaware,2579,3187,2.2,73.41,15.8,25,Good
9,Georgia,9048,5874,2.8,72.54,10.1,186,Good

In [36]:
more_frost.head()

      State  Population  Income  Illiteracy  Life_Exp  Murder  Frost   remarks
0   Alabama       21252    4456         0.6     69.93     4.3    173  not good
8   Florida       12755    4138         1.6     73.84     3.4    171      Good
9   Georgia        9048    5874         2.8     72.54    10.1    186      Good
13  Indiana       16658    4620         2.7     72.50     3.1    190      Good
18    Maine       11446    3456         1.2     69.11     1.0    184  not good

In [37]:
# concatenating the two frames
new_df = pd.concat([more_death, more_frost])
new_df.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,remarks
2,Arizona,1169,5298,1.0,72.55,9.2,150,Good
5,Colorado,20082,4083,2.5,73.11,9.0,96,Good
6,Connecticut,2882,5261,1.2,72.40,14.3,49,Good
7,Delaware,2579,3187,2.2,73.41,15.8,25,Good
9,Georgia,9048,5874,2.8,72.54,10.1,186,Good

## Handling Null values

In [38]:
# Creating Null values
states.loc[0:2, 'Life_Exp'] = np.nan
states.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,remarks
0,Alabama,21252,4456,0.6,NaN,4.3,173,not good
1,Alaska,18170,3356,2.0,NaN,2.4,154,not good
2,Arizona,1169,5298,1.0,NaN,9.2,150,Good
3,Arkansas,9415,6315,2.7,73.31,3.4,71,Good
4,California,5394,3881,2.9,70.36,2.4,88,average

In [39]:
# finding out how many null values are there
states.isnull().sum()

State         0
Population    0
Income        0
Illiteracy    0
Life_Exp      3
Murder        0
Frost         0
remarks       0
dtype: int64

In [40]:
# # simple fillna
# states.fillna(100, inplace=True)
# states.head()

In [41]:
# filling with mean
states.fillna(states['Life_Exp'].mean(), inplace=True)
states.head()

,State,Population,Income,Illiteracy,Life_Exp,Murder,Frost,remarks
0,Alabama,21252,4456,0.6,71.659149,4.3,173,not good
1,Alaska,18170,3356,2.0,71.659149,2.4,154,not good
2,Arizona,1169,5298,1.0,71.659149,9.2,150,Good
3,Arkansas,9415,6315,2.7,73.310000,3.4,71,Good
4,California,5394,3881,2.9,70.360000,2.4,88,average

In [42]:
# we can also use .interpolate(), or mode in place of .mean(), it will fill the value according to a pattern
# or we can drop the null rows
states.dropna(inplace=True)

# We can also drop rows according to specific columns
states.dropna(subset=["Life_Exp"], inplace=True) # drop the row if the life_exp in that is null

# to get the na value of a specific column
states[states["Life_Exp"].isna()]  # isnull == isna  notnull == notna

Empty DataFrame
Columns: [State, Population, Income, Illiteracy, Life_Exp, Murder, Frost, remarks]
Index: []

## Aggregating Data

In [43]:
# prints no. of counts each value have
states['remarks'].value_counts()
# We can make it more elaborate using more filters
# states[states['Frost'] > 170]['remarks'].value_counts()

remarks
Good        23
not good    14
average     13
Name: count, dtype: int64

In [44]:
# value counts of remarks in which state have a frost of great than 170
states[states['Frost'] > 170]['remarks'].value_counts()

remarks
Good        6
not good    3
Name: count, dtype: int64

In [45]:
states.groupby(["remarks"])["Frost"].sum().mean()

1711.0

In [47]:
pivot_table = states.pivot_table(values=['Income', 'Population'], index='remarks', aggfunc='sum')
print(pivot_table)

          Income  Population
remarks
Good      105037      210316
average    57982      181371
not good   70680      157052